export const localizationConstant = {
	uploadingAvatar: 'Uploading Avatar..',
	save: 'Save',
	uploadingFile: 'Uploading file...',
	chooseFile: 'Choose File',
	noFileChosen: 'No file chosen',
	welcomeTo: 'Welcome to',
	reelAnalytics: 'Reel Analytics',
	poweredBy: 'Powered By',
	nextEdgeSports: 'NextEdge Sports',
	searchForPlayers: 'Search for players',
	imperial: 'Imperial',
	metric: 'Metric',
	playerInfo: 'Player Info',
	bioInfo: 'Bio Info',
	position: 'Position',
	classOf: 'Class Of',
	collegeProjection: 'College Projection',
	state: 'State',
	scores: 'Scores',
	igaScore: 'IGA Score',
	productionScore: 'Production Score',
	raScore: 'RA Score',
	actScore: 'ACT Score',
	satScore: 'SAT Score',
	academicsOther: 'Academics / other',
	highSchool: 'High School',
	offerCount: 'Offer Count',
	selectMultipleForShortlists: 'Select multiple for shortlists',
	selectPlayersToBeAddedInShortlist: 'Select players to be added in shortlist',
	cancel: 'Cancel',
	addToShortlist: 'Add to shortlist',
	addToPropspectlist: 'Add to prospect list',
	compare: 'Compare',
	statsWithOtherPlayers: 'stats with other players',
	back: 'Back',
	bigThreeScores: 'Big Three Scores',
	undercruited: 'Undercruited',
	playerTags: 'Player Tags',
	viewAll: 'View all',
	teamGrade: 'Team Grade',
	height: 'Height',
	heightIn: 'Height (in)',
	weight: 'Weight',
	birthdate: 'Birthdate',
	yearsStarter: 'Years Starter',
	secondaryPosition: 'Secondary Position',
	playerIDColor: 'Player Id Color',
	playerCollegeIdColor: 'Player College Id Color',
	yourInterest: 'Your Interest',
	quicknote: 'Quicknote',
	evaluation: 'Evaluation',
	addToDashboard: 'Add to dashboard',
	tagName: 'Tag Name',
	create: 'Create',
	allPlayerTags: 'All Player Tags',
	tagCreatedBy: 'Tag created by',
	select: 'Select',
	quickNote: 'Quick Note',
	addQuickNote: 'Add quick note',
	submit: 'Submit',
	addEvaluation: 'Add Evaluation',
	editingEvaluationBy: 'Editing Evaluation by',
	viewingEvaluationBy: 'Viewing Evaluation by',
	heightFtIn: 'Height (ft & in)',
	weightLbs: 'Weight (lbs)',
	birthDate: 'Birth Date',
	country: 'Country',
	currentAge: 'Current Age',
	commitmentStatus: 'Commitment Status',
	evaluatedBy: 'Evaluated By',
	highSchoolTranscript: 'High School Transcript',
	fortyYardTime: '40 Yard Time',
	fortyYardTimeSec: '40 Yard Time (sec)',
	hundredYard: '100 Yard',
	hundredYardSec: '100 Yard (sec)',
	shuttle: 'Shuttle',
	shuttleSec: 'Shuttle (sec)',
	threeCone: '3 - Cone',
	threeConeSec: '3 - Cone (sec)',
	benchPressMax: 'Bench Press Max',
	benchPressMaxWt: 'Bench Press Max (wt)',
	reps: 'Reps',
	squatMax: 'Squat Max',
	squatMaxWt: 'Squat Max (wt)',
	clean: 'Clean',
	cleanWt: 'Clean (wt)',
	verticalJump: 'Vertical Jump',
	verticalJumpInches: 'Vertical Jump (inches)',
	broadJump: 'Broad Jump',
	broadJumpFeet: 'Broad Jump (feet)',
	rank: 'Rank',
	score: 'Score',
	commitment: 'Commitment',
	committed: 'Committed',
	committedElsewhere: 'Committed elsewhere',
	offered: 'Offered',
	bubblePlayer: 'Bubble player',
	notOffering: 'Not offering',
	communicationStatus: 'Communication status',
	lastPhoneCall: 'Last phone call',
	lastMail: 'Last mail',
	lastFaceToFaceMeeting: 'Last face to face meeting',
	lastHomeVisit: 'Last home visit',
	lastOnCampusVisit: 'Last On-campus visit',
	areYouSureYouWantToRemovePlayerColor: 'Are you sure you want to remove player color ?',
	latest: 'Latest',
	raRank: 'RA Rank',
	igaRank: 'IGA Rank',
	prodScore: 'PROD Score',
	prodRank: 'PROD Rank',
	noBestAttributeAvailable: 'No best attribute available.',
	noWorstAttributeAvailable: 'No worst attribute available.',
	noSchemeFitAvailable: 'No scheme fit available.',
	noCoachSummaryAvailable: 'No coach summary available.',
	noQuickNoteAdded: 'No quick note added.',
	videoClip: 'Video clip',
	comingSoon: 'Coming soon',
	comingSoonText: 'We are working to serve you the best experience of this feature.',
	stayTunedForNextUpdate: 'Stay tuned for next update.',
	createShortlist: 'Create shortlist',
	noShortlistsAreAvailableCreateYourShortlistNow: 'No shortlists are available. Create your shortlist now.',
	renameShortlist: 'Rename Shortlist',
	deleteShortlist: 'Delete Shortlist',
	changeTheme: 'Change Theme',
	lastCreated: 'Last created',
	playersShortlisted: 'Players Shortlisted',
	createdOn: 'Created On',
	avgRAScore: 'Avg RA score',
	avgIGAScore: 'Avg IGA score',
	avgPRODScore: 'Avg PROD score',
	showShortlist: 'Show shortlist',
	selectName: 'Select name',
	areYouSureYouWantToDeleteThisShortlist: 'Are you sure you want to delete this Shortlist ?',
	delete: 'Delete',
	changeColor: 'Change Color',
	selectTheme: 'Select Theme',
	continue: 'Continue',
	skip: 'Skip',
	pinnedPlayers: 'Pinned players',
	selectedPlayer: 'Selected player',
	noPlayersAreAvailable: 'No players are available',
	recruitingDashboard: 'Recruiting Dashboard',
	createNewBoard: 'Create new board',
	createRecruitingDashboard: 'Create Recruiting Dashboard',
	noDashboardsAreAvailableCreateYourDashboardNow: 'No dashboards are available. Create your dashboard now.',
	renameDashboard: 'Rename Dashboard',
	deleteDashboard: 'Delete Dashboard',
	showRecruitingDashboard: 'Show recruiting dashboard',
	areYouSureYouWantToDeleteThisDashboard: 'Are you sure you want to delete this Dashboard?',
	forgotPassword: 'Forgot password',
	login: 'Login',
	backToLogin: 'Back to login',
	sendMail: 'Send mail',
	savePassword: 'Save password',
	showMoreFilter: 'Show more filter',
	showLessFilter: 'Show less filter',
	downloadCsvFile: 'Download csv file',
	downloadPdforExcel: 'Download PDF or EXCEl',
	pinnedProfiles: 'Pinned Profiles',
	blitzComparison: 'Blitz Comparison',
	addToRecruitingDashboard: 'Add to recruiting dashboard',
	maxSpeed: 'Max Speed',
	timeToMaxSpeed: 'Time To Max Speed',
	avgYardsOfSeparationCreated: 'Avg. Yards Of Separation Created',
	avgTransitionTime: 'Avg. Transition Time',
	avgYardAfterCatchYAC: 'Avg. Yard After Catch (YAC)',
	sizeFactor: 'Size Factor',
	yardsReception: 'Yards/Reception',
	yards: 'Yards',
	touchdowns: 'Touchdowns',
	interceptions: 'Interceptions',
	tacklesForLoss: 'Tackles For Loss',
	rACollegeProjection: 'RA College Projection',
	reelAnalyticsProjection: 'Reel Analytics Projection',
	communication: 'Communication',
	coachProjection: "Coach's Projection",
	highSchoolCoachProjection: 'High School Coach Projection',
	myProjection: 'My Projection',
	videoSource: 'Video Source',
	igaranking: 'IGA ranking',
	igaMetrics: 'IGA Metrics',
	igaCombineComparisons: 'IGA / Combine Comparisons',
	highSchoolCoachsEvaluation: "High School Coach's Evaluation",
	highSchoolCoachPlayerSummary: "High School Coach's Player Summary",
	bestAttribute: 'BEST ATTRIBUTE - Area of Strength',
	worstAttribute: 'WORST ATTRIBUTE - Area of Weakness',
	schemeFit: 'Scheme Fit',
	rAScoringVideos: 'RA Scoring Videos',
	bigThreeRanking: 'Big 3 Ranking',
	coachQuickNote: "Coach's Quick Note",
	coachEvaluation: "Coach's Evaluation",
	highSchoolTranscriptDocument: 'High school transcript document',
	viewProfile: 'View profile',
	apply: 'Apply',
	editShortlistName: 'Edit shortlist name',
	editDashboardName: 'Edit dashboard name',
	newPassword: 'New Password',
	confirmPassword: 'Confirm Password',
	resetPassword: 'Reset Password',
	logout: 'Logout',
	positionRank: 'Position rank',
	overallRank: 'Overall rank',
	currentlySelected: 'Currently Selected',
	playerRAScore: 'Player RA Score',
	welcomeToNextEdgeSports: 'Welcome to NextEdge Sports.',
	nextEdgeSportsDescription:
		'NextEdge Sports is a Global Saas Sports Tech Company. We empower the key stakeholders of the sports industry: teams, leagues, federations, and clubs, to excel in the four pillars of the digital sports ecosystem; operations, analytics, performance, and revenue generation, on and off the field.',
	provideDescription:
		'We provide a full suite of fully integrated software solutions in an industry first-of-a-kind cloud-based platform to achieve this. Our development and engineering teams have built industry-leading software platforms for the NFL and PGA to name a few. NextEdge Sports Solutions are powered by AI, machine learning, blockchain and cutting-edge tech stack featuring AWS.',
	launchedDescription:
		'We have now launched our flagship product, Edge360, a revolutionary, GDPR compliant cloud-based solution, that will empower you to take your digital ecosystem to new levels. Edge360 aims to help you set new standards in facilitating, enhanced internal and external collaboration, while providing you with deeper insights, improved performance, and better decision making on and off the playing field!',
	reelAnalyticsDescription:
		"Reel Analytics (formerly Recruiting Analytics) is a sports technology and data company that analyzes video to measure in-game athleticism so coaches can evaluate players more accurately. With Reel Analytics' player tracking technology, previously unavailable athleticism data is now available for objective player evaluations and reliable projections.",
	reelAnalyticsScoringMethodology: 'Reel Analytics Scoring Methodology:',
	reelAnalyticsMethodologyDescription:
		'Reel Analytics’ evaluation methodology consists of two main factors: an In-Game Athleticism Score (IGA Score) and a Production Score (PROD Score), which are both used to determine the RA Score that serves as the final overall player grade. Reel Analytics’ IGA Score derives from position-specific athleticism metrics extracted by our tracking technology, and Reel Analytics’ PROD Score derives from objective advanced performance metrics. Each metric is collected and inputted into a data range, then allocated points based on the range in which they fall. The points from each metric are weighed into the final score for each category. Then, consistent with our belief that accurately projecting a player’s success is a function of their athletic ability and their impact on the game, we integrate these two variables into the prospects’ RA Score — the final evaluation grade for each player. Reel Analytics uses the players’ overall RA Score to project their ceiling at the next level.',
	selectAPlayer: 'Select a Player',
	allPlayers: 'All players',
	pinnedPlayer: 'Pinned player',
	noDataAvailable: 'No data available.',
	iga: 'IGA',
	ra: 'RA',
	prod: 'PROD',
	areYouSureYouWantToAddThesePlayersTo: 'Are you sure you want to add these players to ',
	goToShortlists: 'Go to shortlists',
	okay: 'Okay',
	selectAnother: 'Select another',
	add: 'Add',
	title: 'Title',
	yes: 'Yes',
	metrics: 'Metrics',
	hundredYardTime: '100 yard time',
	team: 'Team',
	shortlists: 'Shortlists',
	createdBy: 'Created By',
	addTo: 'Add to',
	addPlayer: 'Add player',
	goToDashboards: 'Go to dashboards',
	goToProspects: 'Go to prospects',
	favorites: 'Favorites',
	sponsoredBy: 'Sponsored by',
	createDashboard: 'Create dashboard',
	noOneAddedQuickNotesForThisPlayer: 'No one added quick notes for this player',
	noShortlistsAvailableCreateYourShortlistNow: 'No shortlists available. Create your shortlist now',
	noShortlistsAreAvailable: 'No shortlists are available.',
	noDashboardAvailableCreateYourDashboardNow: 'No dashboard available. Create your dashboard now',
	noOneHasEvaluatedThisPlayerYet: 'No one has evaluated this player yet.',
	noPlayersAreAvailableForSelection: 'No players are available for selection',
	noPlayersInThisPositionAreAvailableForSelection: 'No players in this position are available for selection',
	noPlayersAreAvailableBasedOnScoreForSelection: 'No players are available based on score for selection',
	noPinnedPlayersAreAvailableForSelection: 'No pinned players are available for selection',
	noPlayerTagsCreatedYet: 'No player tags created yet.',
	admin: 'Admin',
	addViewTeam: 'Add / View Team & Admin',
	addViewRoster: 'Add / View Roster',
	addViewSponser: 'Add / View Sponser',
	addViewCoachesUsers: 'Add / View Coaches Users',
	addViewUniversityCollegeContacts: 'Add / View University / College Contacts',
	addViewSchedule: 'Add / View Schedule',
	addViewTeamDescription: 'Add details of each team and their admin in the entire organization / school',
	addViewRosterDescription: 'Add details of players on each team in the organization / school',
	addViewSponserDescription: 'Add details of each team and their admin in the entire organization / school ',
	addViewCoachesUsersDescription: 'Add details of each team and their admin in the entire organization / school',
	addViewUniversityCollegeContactsDescription:
		'Add details of each university for prospect introductions for recruiting purposes from any player within the organization / school',
	addViewScheduleDescription: "Add details of each team's schedule within the organization / school.",
	nameOfTeam: 'Name of Team',
	teamLevel: 'Team Level',
	headCoach: 'Head Coach',
	adminName: 'Admin Name',
	adminFirstName: 'Admin First Name',
	adminLastName: 'Admin Last Name',
	emailAddress: 'Email Address',
	phoneNumber: 'Phone Number',
	roleOnTeam: 'Role On Team',
	organizationName: 'Organization Name',
	organizationLevel: 'Organization Level',
	teamName: 'Team Name',
	teamSport: 'Team Sport',
	teamGender: 'Team Gender',
	headCoachFirstName: 'Head Coach First Name',
	headCoachLastName: 'Head Coach Last Name',
	headCoachEmail: 'Head Coach Email',
	headCoachPhoneNumber: 'Head Coach Phone Number',
	season: 'Season',
	personalInfoTeamAdmin: 'Personal Info Team Admin',
	organizationInfo: 'Organization Info',
	teamInfo: 'Team Info',
	teamsList: 'Teams List',
	addNewTeam: 'Add new team',
	viewTeamList: 'View team list',
	addedTeam: 'Added Team',
	myAddressBook: 'My Address Book',
	edgeAddressBook: 'Edge Address Book',
	selectMultiple: 'Select multiple',
	importToMyAddressBook: 'Import to My Address Book',
	editMyAddressBook: 'Edit My Address Book',
	update: 'Update',
	viewEnteredTeamList: 'View Entered Team List',
	uploadExcelFile: 'Upload EXCEL file',
	downloadSampleExcel: 'Download sample EXCEL',
	editTeam: 'Edit Team',
	enterNewTeam: 'Enter New Team',
	areYouSureYouWantToDeleteThisTeam: 'Are you sure you want to delete this team?',
	saveAndAddNewTeam: 'Save & add new team',
	saveAndAddRoster: 'Save & add roster',
	saveChanges: 'Save changes',
	share: 'Share',
	division: 'Division',
	coachingRole: 'Coaching Role',
	universityCollegeContacts: ' University / College Contacts',
	addUniversityCollege: 'Add University / College',
	enterUniversityCollegeContacts: 'Enter University / College Contacts',
	editUniversityCollegeContacts: 'Edit University / College Contacts',
	viewUniversityCollegeList: 'View University / College List',
	enteredUniversities: 'Entered Universities',
	viewEnteredUniversity: 'View Entered University',
	areYouSureYouWantToDeleteThisUniversity: 'Are you sure you want to delete this University?',
	universityInfo: 'University Info',
	nameOfCollege: 'Name of College',
	coachFirstName: "Coach's First Name",
	coachLastName: "Coach's Last Name",
	saveAndUniversityCollege: 'Save & University / College',
	editUniversityCollege: 'Edit University / College',
	schoolSize: 'School Size',
	importFromEdgeAddressBook: 'Import from Edge Address Book',
	gender: 'gender',
	sports: 'Sports',
	address: 'Address',
	playersList: 'Players List',
	addNewPlayer: ' Add new player',
	editPlayer: 'Edit Player',
	enterNewPlayer: 'Enter New Player',
	viewPlayerList: 'View player list',
	viewRoster: 'View Roster',
	addedPlayer: 'Added Player',
	viewEnteredPlayerList: 'View Entered Player List',
	personalInfo: 'Personal Info',
	projectionsAndCombineMetrics: 'Projections & Combine Metrics',
	combineMetrics: 'Combine Metrics',
	socialInfo: 'Social Info',
	guardian: 'Guardian',
	academicScores: 'Academic Scores',
	achievements: 'Achievements',
	playerFirstName: 'Player First Name',
	playerLastName: 'Player Last Name',
	jerseyNumber: 'Jersey Number',
	email: 'Email',
	playerEmail: 'Player Email',
	primaryPosition: 'Primary Position',
	dateOfBirth: 'Date Of Birth',
	countryOfBirth: 'Country Of Birth',
	stateProvinceofBirth: 'State/Province of Birth',
	clearingHouseNumber: 'Clearing House Number',
	clearingHouse: 'Clearing House Number !',
	optInRecruiting: 'Opt in Recruiting',
	coachCollegeProjection: "Coach's College Projection",
	twitter: 'Twitter',
	instagram: 'Instagram',
	hudl: 'Hudl',
	tikTok: 'Tik Tok',
	name: 'Name',
	relationship: 'Relationship',
	primaryGuardian: 'Primary Guardian',
	secondaryGuardian: 'Secondary Guardian',
	gpaScore: 'GPA Score',
	transcript: 'Transcript',
	act: 'ACT',
	sat: 'SAT',
	athletic: 'Athletic',
	academic: 'Academic',
	addDocument: 'Add Document',
	academicSummary: 'Academic Summary',
	athleticSummary: 'Athletic Summary',
	saveAndNewPlayer: 'Save & Add New Player',
	areYouSureYouWantToDeleteThisField: 'Are you sure you want to delete this field?',
	createProspect: 'Create Prospect',
	createProspectListForSharing: 'Create prospect list for Sharing',
	createProspectSharingList: 'Create prospect sharing list',
	createProspectGradingList: 'Create prospect grading list',
	createProspectListForGrading: 'Create prospect list for Grading',
	noProspectListsAreAvailable: 'No prospect lists are available.',
	prospectsSharingList: 'Prospects Sharing List',
	prospectsGradingList: 'Prospects Grading List',
	renameProspect: 'Rename Prospect',
	deleteProspect: 'Delete Prospect',
	areYouSureYouWantToDeleteThisProspectList: 'Are you sure you want to delete this Prospect list ?',
	showProspectList: 'Show prospect list',
	shareProspectList: 'Share prospect list',
	noOfPlayers: 'No of players',
	options: 'Options',
	more: 'More',
	excelOptions: 'Excel Options',
	viewAllProspectList: 'View All Prospect List',
	createProspectsList: 'Create Prospects List',
	noUniversitiesAreAvailable: 'No universities are available',
	searchUniversity: 'Search by university',
	areYouSureYouWantToShareThisProspectList: 'Are you sure you want to Share this Prospect list ?',
	no: 'No',
	playersMatrix: 'Players Matrix',
	reelAnalyticsCollegeProjection: 'Reel Analytics College Projection',
	areYouSureYouWantToImportSelectedUniversityIntoMyAddressBook:
		'Are you sure you want to import selected university into my address book ?',
	pleaseEnterValidEmail: 'Please enter valid email.',
	emojiNotAllowed: 'Emoji not allowed.',
	collegeReadiness: 'College Readiness',
	mandatoryFields: 'Mandatory Fields',
	prospectGradingList: 'Prospect Grading List',
	addScore: 'Add score',
	sharedBy: 'Shared by',
	sharedDate: 'Shared Date',
	submittedDate: 'Submitted Date',
	notifications: 'Notifications'
};
